language: java

sudo: false

jdk:
  - oraclejdk8

branches:
  only:
    - master

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - mvaduva87@gmail.com